DROP VIEW IF EXISTS analytics.workspace_price_insights_v2 CASCADE;

CREATE OR REPLACE VIEW analytics.workspace_price_insights_v2 AS
 WITH price_points AS (
         SELECT a."userId",
            a."sellerConnectionId",
            a.marketplace,
            a."marketplaceId",
            a.sku,
            max(a.asin) AS asin,
            max(a.currency_code) AS currency_code,
            a.price,
            count(DISTINCT a.order_date) AS days_seen,
            sum(a.orders) AS orders,
            sum(a.units) AS units,
            sum(a.revenue) AS revenue,
            sum(a.profit_before_ads) AS profit_before_ads,
            sum(a.ads_spend_allocated) AS ads_spend,
            sum(a.profit) AS profit,
            sum(a.impressions_allocated) AS impressions,
            sum(a.clicks_allocated) AS clicks,
            sum(a.ads_units_allocated) AS ads_units,
            sum(a.ads_sales_revenue_allocated) AS ads_sales_revenue,
            avg(a.units) AS avg_daily_units,
            avg(a.revenue) AS avg_daily_revenue,
            avg(a.profit) AS avg_daily_profit,
            avg(a.ads_spend_allocated) AS avg_daily_ads_spend,
            stddev_samp(a.units) AS stddev_daily_units
           FROM analytics.workspace_day_price_allocated_v2 a
          GROUP BY a."userId", a."sellerConnectionId", a.marketplace, a."marketplaceId", a.sku, a.price
        ), scored_base AS (
         SELECT pp."userId",
            pp."sellerConnectionId",
            pp.marketplace,
            pp."marketplaceId",
            pp.sku,
            pp.asin,
            pp.currency_code,
            pp.price,
            pp.days_seen,
            pp.orders,
            pp.units,
            pp.revenue,
            pp.profit_before_ads,
            pp.ads_spend,
            pp.profit,
            pp.impressions,
            pp.clicks,
            pp.ads_units,
            pp.ads_sales_revenue,
            pp.avg_daily_units,
            pp.avg_daily_revenue,
            pp.avg_daily_profit,
            pp.avg_daily_ads_spend,
            pp.stddev_daily_units,
                CASE
                    WHEN pp.days_seen < 2 THEN 0::numeric
                    WHEN pp.avg_daily_units IS NULL OR pp.avg_daily_units = 0::numeric THEN 0::numeric
                    ELSE GREATEST(0::numeric, LEAST(1::numeric, 1::numeric - COALESCE(pp.stddev_daily_units, 0::numeric) / NULLIF(pp.avg_daily_units, 0::numeric)))
                END AS confidence_per_price
           FROM price_points pp
        ), scored AS (
         SELECT s."userId",
            s."sellerConnectionId",
            s.marketplace,
            s."marketplaceId",
            s.sku,
            s.asin,
            s.currency_code,
            s.price,
            s.days_seen,
            s.orders,
            s.units,
            s.revenue,
            s.profit_before_ads,
            s.ads_spend,
            s.profit,
            s.impressions,
            s.clicks,
            s.ads_units,
            s.ads_sales_revenue,
            s.avg_daily_units,
            s.avg_daily_revenue,
            s.avg_daily_profit,
            s.avg_daily_ads_spend,
            s.stddev_daily_units,
            s.confidence_per_price,
            s.revenue / NULLIF(s.days_seen, 0)::numeric AS revenue_per_day,
            s.profit / NULLIF(s.days_seen, 0)::numeric AS profit_per_day,
            s.ads_spend / NULLIF(s.days_seen, 0)::numeric AS ads_spend_per_day,
            s.ads_sales_revenue / NULLIF(s.days_seen, 0)::numeric AS ads_sales_per_day,
            s.clicks / NULLIF(s.impressions, 0::numeric) AS ctr,
            s.ads_spend / NULLIF(s.clicks, 0::numeric) AS cpc,
            s.ads_sales_revenue / NULLIF(s.ads_spend, 0::numeric) AS roas,
            s.ads_spend / NULLIF(s.ads_sales_revenue, 0::numeric) AS acos,
            s.ads_spend / NULLIF(s.revenue, 0::numeric) AS tacos,
            s.orders / NULLIF(s.clicks, 0::numeric) AS orders_per_click,
                CASE
                    WHEN s.days_seen >= 7 AND s.units >= 20::numeric AND s.confidence_per_price >= 0.5 THEN 'High'::text
                    WHEN s.days_seen >= 3 AND s.units >= 10::numeric THEN 'Medium'::text
                    WHEN s.days_seen >= 2 THEN 'Low'::text
                    ELSE 'Very Low'::text
                END AS confidence_label,
            s.days_seen >= 3 AND s.units >= 10::numeric AND s.confidence_per_price >= 0.3 AS is_effective_price_point,
            s.days_seen >= 7 AND s.units >= 20::numeric AND s.confidence_per_price >= 0.5 AS is_modeling_price_point
           FROM scored_base s
        ), ranked AS (
         SELECT s."userId",
            s."sellerConnectionId",
            s.marketplace,
            s."marketplaceId",
            s.sku,
            s.asin,
            s.currency_code,
            s.price,
            s.days_seen,
            s.orders,
            s.units,
            s.revenue,
            s.profit_before_ads,
            s.ads_spend,
            s.profit,
            s.impressions,
            s.clicks,
            s.ads_units,
            s.ads_sales_revenue,
            s.avg_daily_units,
            s.avg_daily_revenue,
            s.avg_daily_profit,
            s.avg_daily_ads_spend,
            s.stddev_daily_units,
            s.confidence_per_price,
            s.revenue_per_day,
            s.profit_per_day,
            s.ads_spend_per_day,
            s.ads_sales_per_day,
            s.ctr,
            s.cpc,
            s.roas,
            s.acos,
            s.tacos,
            s.orders_per_click,
            s.confidence_label,
            s.is_effective_price_point,
            s.is_modeling_price_point,
            row_number() OVER (PARTITION BY s."userId", s.marketplace, s.sku ORDER BY s.profit_per_day DESC NULLS LAST, s.price) AS profit_rank,
            row_number() OVER (PARTITION BY s."userId", s.marketplace, s.sku ORDER BY s.revenue_per_day DESC NULLS LAST, s.price) AS revenue_rank,
                CASE
                    WHEN s.is_modeling_price_point = true THEN row_number() OVER (PARTITION BY s."userId", s.marketplace, s.sku, s.is_modeling_price_point ORDER BY s.profit_per_day DESC NULLS LAST, s.price)
                    ELSE NULL::bigint
                END AS modeling_profit_rank,
                CASE
                    WHEN s.is_modeling_price_point = true THEN row_number() OVER (PARTITION BY s."userId", s.marketplace, s.sku, s.is_modeling_price_point ORDER BY s.revenue_per_day DESC NULLS LAST, s.price)
                    ELSE NULL::bigint
                END AS modeling_revenue_rank
           FROM scored s
        )
 SELECT "userId",
    "sellerConnectionId",
    marketplace,
    "marketplaceId",
    sku,
    asin,
    currency_code,
    price,
    days_seen,
    orders,
    units,
    revenue,
    profit_before_ads,
    ads_spend,
    profit,
    impressions,
    clicks,
    ads_units,
    ads_sales_revenue,
    avg_daily_units,
    avg_daily_revenue,
    avg_daily_profit,
    avg_daily_ads_spend,
    stddev_daily_units,
    confidence_per_price,
    revenue_per_day,
    profit_per_day,
    ads_spend_per_day,
    ads_sales_per_day,
    ctr,
    cpc,
    roas,
    acos,
    tacos,
    orders_per_click,
    confidence_label,
    is_effective_price_point,
    is_modeling_price_point,
    profit_rank,
    revenue_rank,
    modeling_profit_rank,
    modeling_revenue_rank
   FROM ranked;
;
