DROP VIEW IF EXISTS analytics.workspace_modeled_prices_v2 CASCADE;

CREATE OR REPLACE VIEW analytics.workspace_modeled_prices_v2 AS
 WITH modeling_points AS (
         SELECT pi."userId",
            pi."sellerConnectionId",
            pi.marketplace,
            pi."marketplaceId",
            pi.sku,
            pi.asin,
            pi.currency_code,
            pi.price,
            pi.days_seen,
            pi.orders,
            pi.units,
            pi.revenue,
            pi.profit_before_ads,
            pi.ads_spend,
            pi.profit,
            pi.impressions,
            pi.clicks,
            pi.ads_units,
            pi.ads_sales_revenue,
            pi.avg_daily_units,
            pi.avg_daily_revenue,
            pi.avg_daily_profit,
            pi.avg_daily_ads_spend,
            pi.stddev_daily_units,
            pi.confidence_per_price,
            pi.revenue_per_day,
            pi.profit_per_day,
            pi.ads_spend_per_day,
            pi.ads_sales_per_day,
            pi.ctr,
            pi.cpc,
            pi.roas,
            pi.acos,
            pi.tacos,
            pi.orders_per_click,
            pi.confidence_label,
            pi.is_effective_price_point,
            pi.is_modeling_price_point,
            pi.profit_rank,
            pi.revenue_rank,
            pi.modeling_profit_rank,
            pi.modeling_revenue_rank
           FROM analytics.workspace_price_insights_v2 pi
          WHERE pi.is_modeling_price_point = true
        ), curve AS (
         SELECT mp."userId" AS user_id,
            max(mp."sellerConnectionId") AS seller_connection_id,
            mp.marketplace,
            max(mp."marketplaceId") AS marketplace_id,
            mp.sku,
            max(mp.asin) AS asin,
            max(mp.currency_code) AS currency_code,
            count(*) AS modeling_price_points,
                CASE
                    WHEN count(*) = 2 THEN 5
                    WHEN count(*) = 3 THEN 7
                    ELSE 9
                END AS modeled_candidate_count,
            min(mp.price) AS min_modeling_price,
            max(mp.price) AS max_modeling_price,
            (array_agg(mp.price ORDER BY mp.revenue_per_day DESC NULLS LAST, mp.price DESC))[1] AS best_observed_revenue_price,
            (array_agg(mp.price ORDER BY mp.profit_per_day DESC NULLS LAST, mp.price DESC))[1] AS best_observed_profit_price,
            GREATEST(0.10, (min(mp.price) + max(mp.price)) / 2.0 * 0.01) AS price_step,
            regr_slope(mp.avg_daily_units::double precision, mp.price::double precision) AS demand_slope,
            regr_intercept(mp.avg_daily_units::double precision, mp.price::double precision) AS demand_intercept,
            regr_slope(mp.profit_per_day::double precision, mp.price::double precision) AS profit_slope,
            regr_intercept(mp.profit_per_day::double precision, mp.price::double precision) AS profit_intercept,
            regr_slope(mp.ads_spend_per_day::double precision, mp.price::double precision) AS ads_slope,
            regr_intercept(mp.ads_spend_per_day::double precision, mp.price::double precision) AS ads_intercept
           FROM modeling_points mp
          GROUP BY mp."userId", mp.marketplace, mp.sku
         HAVING count(*) >= 2
        ), observed_candidates AS (
         SELECT mp."userId" AS user_id,
            mp."sellerConnectionId" AS seller_connection_id,
            mp.marketplace,
            mp."marketplaceId" AS marketplace_id,
            mp.sku,
            mp.asin,
            mp.currency_code,
            'observed'::text AS candidate_type,
            mp.price AS candidate_price,
            mp.avg_daily_units AS expected_daily_units,
            mp.revenue_per_day AS expected_daily_revenue,
            mp.ads_spend_per_day AS expected_daily_ads_spend,
            mp.profit_per_day AS expected_daily_profit,
            c.modeling_price_points,
            c.modeled_candidate_count,
            c.demand_slope,
            c.demand_intercept,
            c.profit_slope,
            c.profit_intercept,
            c.ads_slope,
            c.ads_intercept,
            c.min_modeling_price,
            c.max_modeling_price,
            c.price_step,
            mp.price AS source_observed_price
           FROM modeling_points mp
             JOIN curve c ON c.user_id = mp."userId" AND c.marketplace = mp.marketplace AND c.sku = mp.sku
        ), price_grid AS (
         SELECT c.user_id,
            c.seller_connection_id,
            c.marketplace,
            c.marketplace_id,
            c.sku,
            c.asin,
            c.currency_code,
            c.modeling_price_points,
            c.modeled_candidate_count,
            c.min_modeling_price,
            c.max_modeling_price,
            c.best_observed_revenue_price,
            c.best_observed_profit_price,
            c.price_step,
            c.demand_slope,
            c.demand_intercept,
            c.profit_slope,
            c.profit_intercept,
            c.ads_slope,
            c.ads_intercept,
            gs.idx,
                CASE
                    WHEN c.best_observed_revenue_price = c.max_modeling_price OR c.best_observed_profit_price = c.max_modeling_price THEN c.max_modeling_price + (c.max_modeling_price * 1.10 - c.max_modeling_price) * gs.idx::numeric / (c.modeled_candidate_count + 1)::numeric
                    WHEN c.best_observed_revenue_price = c.min_modeling_price OR c.best_observed_profit_price = c.min_modeling_price THEN c.min_modeling_price * 0.90 + (c.min_modeling_price - c.min_modeling_price * 0.90) * gs.idx::numeric / (c.modeled_candidate_count + 1)::numeric
                    ELSE c.min_modeling_price + (c.max_modeling_price - c.min_modeling_price) * gs.idx::numeric / (c.modeled_candidate_count + 1)::numeric
                END AS raw_candidate_price
           FROM curve c
             CROSS JOIN LATERAL generate_series(1, c.modeled_candidate_count) gs(idx)
        ), modeled_candidates AS (
         SELECT DISTINCT ON (x.user_id, x.marketplace, x.sku, x.candidate_price) x.user_id,
            x.seller_connection_id,
            x.marketplace,
            x.marketplace_id,
            x.sku,
            x.asin,
            x.currency_code,
            'modeled'::text AS candidate_type,
            x.candidate_price,
            GREATEST(x.demand_intercept + x.demand_slope * x.candidate_price::double precision, 0::double precision)::numeric AS expected_daily_units,
            x.candidate_price * GREATEST(x.demand_intercept + x.demand_slope * x.candidate_price::double precision, 0::double precision)::numeric AS expected_daily_revenue,
            GREATEST(x.ads_intercept + x.ads_slope * x.candidate_price::double precision, 0::double precision)::numeric AS expected_daily_ads_spend,
            (x.profit_intercept + x.profit_slope * x.candidate_price::double precision)::numeric AS expected_daily_profit,
            x.modeling_price_points,
            x.modeled_candidate_count,
            x.demand_slope,
            x.demand_intercept,
            x.profit_slope,
            x.profit_intercept,
            x.ads_slope,
            x.ads_intercept,
            x.min_modeling_price,
            x.max_modeling_price,
            x.price_step,
            NULL::numeric AS source_observed_price
           FROM ( SELECT pg.user_id,
                    pg.seller_connection_id,
                    pg.marketplace,
                    pg.marketplace_id,
                    pg.sku,
                    pg.asin,
                    pg.currency_code,
                    pg.modeling_price_points,
                    pg.modeled_candidate_count,
                    pg.min_modeling_price,
                    pg.max_modeling_price,
                    pg.best_observed_revenue_price,
                    pg.best_observed_profit_price,
                    pg.price_step,
                    pg.demand_slope,
                    pg.demand_intercept,
                    pg.profit_slope,
                    pg.profit_intercept,
                    pg.ads_slope,
                    pg.ads_intercept,
                    pg.idx,
                    pg.raw_candidate_price,
                    round(round(pg.raw_candidate_price / pg.price_step) * pg.price_step, 2) AS candidate_price
                   FROM price_grid pg) x
          WHERE x.candidate_price > 0::numeric
        )
 SELECT observed_candidates.user_id,
    observed_candidates.seller_connection_id,
    observed_candidates.marketplace,
    observed_candidates.marketplace_id,
    observed_candidates.sku,
    observed_candidates.asin,
    observed_candidates.currency_code,
    observed_candidates.candidate_type,
    observed_candidates.candidate_price,
    observed_candidates.expected_daily_units,
    observed_candidates.expected_daily_revenue,
    observed_candidates.expected_daily_ads_spend,
    observed_candidates.expected_daily_profit,
    observed_candidates.modeling_price_points,
    observed_candidates.modeled_candidate_count,
    observed_candidates.demand_slope,
    observed_candidates.demand_intercept,
    observed_candidates.profit_slope,
    observed_candidates.profit_intercept,
    observed_candidates.ads_slope,
    observed_candidates.ads_intercept,
    observed_candidates.min_modeling_price,
    observed_candidates.max_modeling_price,
    observed_candidates.price_step,
    observed_candidates.source_observed_price
   FROM observed_candidates
UNION ALL
 SELECT modeled_candidates.user_id,
    modeled_candidates.seller_connection_id,
    modeled_candidates.marketplace,
    modeled_candidates.marketplace_id,
    modeled_candidates.sku,
    modeled_candidates.asin,
    modeled_candidates.currency_code,
    modeled_candidates.candidate_type,
    modeled_candidates.candidate_price,
    modeled_candidates.expected_daily_units,
    modeled_candidates.expected_daily_revenue,
    modeled_candidates.expected_daily_ads_spend,
    modeled_candidates.expected_daily_profit,
    modeled_candidates.modeling_price_points,
    modeled_candidates.modeled_candidate_count,
    modeled_candidates.demand_slope,
    modeled_candidates.demand_intercept,
    modeled_candidates.profit_slope,
    modeled_candidates.profit_intercept,
    modeled_candidates.ads_slope,
    modeled_candidates.ads_intercept,
    modeled_candidates.min_modeling_price,
    modeled_candidates.max_modeling_price,
    modeled_candidates.price_step,
    modeled_candidates.source_observed_price
   FROM modeled_candidates;
;
