DROP MATERIALIZED VIEW IF EXISTS analytics.workspace_price_insights_cache_v2 CASCADE;

CREATE MATERIALIZED VIEW analytics.workspace_price_insights_cache_v2 AS
 SELECT "userId",
    "sellerConnectionId",
    marketplace,
    "marketplaceId",
    sku,
    asin,
    currency_code,
    price,
    days_seen,
    orders,
    units,
    revenue,
    profit_before_ads,
    ads_spend,
    profit,
    impressions,
    clicks,
    ads_units,
    ads_sales_revenue,
    avg_daily_units,
    avg_daily_revenue,
    avg_daily_profit,
    avg_daily_ads_spend,
    stddev_daily_units,
    confidence_per_price,
    revenue_per_day,
    profit_per_day,
    ads_spend_per_day,
    ads_sales_per_day,
    ctr,
    cpc,
    roas,
    acos,
    tacos,
    orders_per_click,
    confidence_label,
    is_effective_price_point,
    is_modeling_price_point,
    profit_rank,
    revenue_rank,
    modeling_profit_rank,
    modeling_revenue_rank
   FROM analytics.workspace_price_insights_v2;
;
