DROP MATERIALIZED VIEW IF EXISTS analytics.workspace_summary_cache_v2 CASCADE;

CREATE MATERIALIZED VIEW analytics.workspace_summary_cache_v2 AS
 SELECT user_id,
    seller_connection_id,
    marketplace,
    marketplace_id,
    sku,
    asin,
    currency_code,
    current_price,
    orders,
    units,
    revenue,
    profit_before_ads,
    ads_spend,
    profit,
    impressions,
    clicks,
    ads_units,
    ads_sales_revenue,
    raw_price_points,
    effective_price_points,
    modeling_price_points,
    best_revenue_price,
    best_revenue_per_day,
    best_revenue_profit_per_day,
    best_revenue_ads_spend_per_day,
    best_revenue_candidate_type,
    best_profit_price,
    best_profit_per_day,
    best_profit_revenue_per_day,
    best_profit_ads_spend_per_day,
    best_profit_candidate_type,
    current_revenue_per_day,
    current_profit_per_day,
    current_ads_spend_per_day,
    revenue_opportunity,
    profit_opportunity,
    tacos,
    roas,
    acos,
    workspace_evidence_label,
    pricing_activity_label
   FROM analytics.workspace_summary_v2;
;
